name: PR Closed
on:
  pull_request: 
    types: 
      - closed
jobs:
  lint:
    name: PR Closed   # job name
    runs-on: ubuntu-latest # the githgub agent/runner where job steps will run/execute
    steps:
      - name: check out the code
        uses: actions/checkout@v4
      - name: PR closed
        run: echo "build is done!"
 
