name: multi job
on: workflow_dispatch
jobs:
  build:
    name: building
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "this is 1st build"
  test:
    name: building1
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "this is 2nd build"
  testdeploy:
    name: building2
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "this is 3rd build"
  devdeploy:
    name: building3
    needs: [ testdeploy ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "this is 4th build"
