name: variable and parameter
on:
  workflow_dispatch:
env:
  TRAINING: "Devops"  # global variable available to all jobs
jobs:
  hello:
    name: greeting   
    runs-on: ubuntu-latest 
    env:
      NAME: "Pallavi"  # local variable available to this job only 
      TRAINING: "BITBUCKET"
    steps:
      - name: check out the code
        uses: actions/checkout@v4
      - name: Greet a user
        run: echo "Hello $NAME! this is my $TRAINING training"
  greeting:
    name: greeting hello  
    env: 
      NAME: "Vaishnavi"  # local variable available to this job only 
    runs-on: ubuntu-latest 
    steps:
      - name: Greet a user
        run: echo "Hello $NAME! this is my $TRAINING training" 
